# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # App Store Connect API 키 설정
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      duration: 1200,
      in_house: false
    )
    
    # 인증서, 프로파일 가져오기 - readonly: true로 변경하고 force_for_new_certificates 추가
    match(
      type: "development", 
      readonly: true,  # 이 부분 true로 변경
      git_basic_authorization: Base64.strict_encode64("#{ENV['GIT_USERNAME']}:#{ENV['GIT_TOKEN']}"),
      force_for_new_certificates: false  # 이 부분 추가
    )
    
    match(
      type: "appstore", 
      readonly: true,  # 이 부분도 true로 변경
      force_for_new_certificates: false  # 이 부분 추가
    )
    
    # 빌드 번호 증가
    increment_build_number(xcodeproj: "PetApp.xcodeproj")
    
    # 앱 빌드 - xcodeproj 파라미터 추가
    build_app(
      scheme: "PetApp",
      xcodeproj: "./PetApp.xcodeproj",  # 이 줄 추가
      export_options: {
        allowProvisioningUpdates: true,
        method: "app-store"  # 이 줄 추가
      },
      xcargs: "-skipPackagePluginValidation -disableAutomaticPackageResolution"
    )
    
    # 테스트플라이트에 업로드
    upload_to_testflight
  end
end