# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(scheme: "PetApp")
  end
  
  desc "Sync certificates and profiles"
  lane :sync_signing do 
    # API 키 접근 대신 Apple ID와 비밀번호 사용
    match(
      type: "appstore",
      app_identifier: "WEDLE.Warala",
      username: ENV["APPLE_ID"]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_signing
    increment_build_number(xcodeproj: "PetApp.xcodeproj")
    build_app(scheme: "PetApp")
    upload_to_testflight(
      username: ENV["APPLE_ID"],
      skip_waiting_for_build_processing: true
    )
  end
end