# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # App Store Connect API 키 설정
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      duration: 1200, # 유효 시간(초)
      in_house: false # 엔터프라이즈 계정인 경우 true
    )

    # 인증서, 프로파일 가져오기
    match(type: "development", readonly: false)
    match(type: "appstore", readonly: false)
    
    # 빌드 번호 증가
    increment_build_number(xcodeproj: "PetApp.xcodeproj")
    
    # 앱 빌드
    build_app(
      scheme: "PetApp",
      export_options: {
        allowProvisioningUpdates: true
      }
    )
    
    # 테스트플라이트에 업로드
    upload_to_testflight
  end
end