name: iOS CI (develop Branch)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: List Schemes
        run: |
          xcodebuild -list -project *.xcodeproj
      - name: Build
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 가장 간단한 방법 - 하드코딩된 기본 시뮬레이터 사용
          xcodebuild build-for-testing -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,name=Any iOS Simulator Device"
      - name: Test
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 가장 간단한 방법 - 하드코딩된 기본 시뮬레이터 사용
          xcodebuild test-without-building -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,name=Any iOS Simulator Device"
