name: iOS CI (Develop Branch)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: Build for iOS device
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Build
        env:
          scheme: PetApp
        run: |
          xcodebuild clean build -scheme "$scheme" -project *.xcodeproj -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO
