name: iOS CI (Develop Branch)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Build
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 특정 iPhone 시뮬레이터 ID를 직접 사용
          xcodebuild build-for-testing -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,name=iPhone 15 Pro,id=3250F3FE-9EB6-42AB-98B3-5D53F4B39F8C"
      - name: Test
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 특정 iPhone 시뮬레이터 ID를 직접 사용
          xcodebuild test-without-building -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,name=iPhone 15 Pro,id=3250F3FE-9EB6-42AB-98B3-5D53F4B39F8C"
