name: iOS CI (Develop Branch)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: List available destinations
        run: |
          xcodebuild -showdestinations -project *.xcodeproj -scheme PetApp
      - name: Build
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 특정 iPhone 시뮬레이터를 사용
          xcodebuild build-for-testing -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder"
      - name: Test
        env:
          scheme: PetApp
          platform: ${{ 'iOS Simulator' }}
        run: |
          # 특정 iPhone 시뮬레이터를 사용
          xcodebuild test-without-building -scheme "$scheme" -project *.xcodeproj -destination "platform=$platform,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder"
