name: iOS CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  beta-deploy:
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      
      - name: Update Matchfile
        run: |
          cat > fastlane/Matchfile << EOL
          git_url("${{ secrets.MATCH_GIT_URL }}")
          storage_mode("git")
          type("appstore")
          app_identifier(["WEDLE.Warala"])
          username("${{ secrets.APPLE_ID }}")
          team_id("${{ secrets.TEAM_ID }}")
          EOL
      
      - name: Setup Provisioning Profile
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          SPACESHIP_SKIP_2FA_UPGRADE: 1
          FASTLANE_DISABLE_COLORS: 1
          FASTLANE_DISABLE_ANIMATION: 1
        run: |
          bundle exec fastlane match appstore --force
      
      - name: Build and upload to TestFlight
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          bundle exec fastlane beta