name: iOS CD (Release Branch)
on:
  push:
    branches: [ "release" ]
jobs:
  deploy-to-testflight:
    name: Build and Deploy to TestFlight
    runs-on: macos-14
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      # App Store Connect API 키 설정
      - name: Setup App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo -n "$APP_STORE_CONNECT_API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      
      # 앱 빌드 및 아카이브
      - name: Build and Archive App
        run: |
          xcodebuild archive \
            -project PetApp.xcodeproj \
            -scheme "PetApp" \
            -archivePath build/app.xcarchive \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            -resolvePackageDependencies
      
      # 디버그: 아카이브 디렉토리 확인
      - name: Check Archive Directory
        run: |
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          ls -la "$RUNNER_TEMP/build"
      
      # ExportOptions.plist 생성
      - name: Create Export Options Plist
        run: |
          cat > ExportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOL
      
      # IPA 생성
      - name: Create IPA
        run: |
          mkdir -p "$RUNNER_TEMP/output"
          xcodebuild -exportArchive \
            -archivePath "$RUNNER_TEMP/build/app.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$RUNNER_TEMP/output" \
            -allowProvisioningUpdates
      
      # 디버그: 빌드 디렉토리 확인
      - name: Check Build Directory
        run: |
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          ls -la "$RUNNER_TEMP/output"
      
      # TestFlight에 업로드
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ runner.temp }}/output/*.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
