name: Upload to TestFlight

on:
  # 수동 트리거를 추가하여 GitHub 웹 인터페이스에서 워크플로우를 실행할 수 있습니다
  workflow_dispatch:
    inputs:
      ipa_path:
        description: '업로드할 IPA 파일 경로'
        required: true
        default: 'builds/app.ipa'
  
  # release 브랜치 푸시 시에도 실행 (필요하면 주석 제거)
  # push:
  #   branches: [ "release" ]

jobs:
  upload-to-testflight:
    name: Upload to TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # IPA 파일을 저장소에 업로드했는지 확인
      - name: Verify IPA exists
        run: |
          ipa_path="${{ github.event.inputs.ipa_path }}"
          if [ -f "$ipa_path" ]; then
            echo "IPA file found at $ipa_path"
          else
            echo "IPA file not found at $ipa_path"
            echo "Please upload your IPA file to the repository in the specified path"
            echo "Or provide a correct path when triggering this workflow"
            exit 1
          fi
      
      # App Store Connect API 키 설정
      - name: Setup App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$APP_STORE_CONNECT_API_KEY" > ~/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      
      # TestFlight에 업로드
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ github.event.inputs.ipa_path }}
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
