name: iOS CD (Release Branch)

on:
  push:
    branches: [ release ]

jobs:
  deploy-to-testflight:
    name: Build and Deploy to TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Cache CocoaPods packages
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Install CocoaPods Dependencies
        run: |
          pod install --repo-update
      
      - name: Setup App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$APP_STORE_CONNECT_API_KEY" > ~/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      
      - name: Setup Apple Developer Authentication
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$APPLE_TEAM_ID"
          xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u "$APPLE_ID" -p "$APPLE_ID_PASSWORD"
      
      - name: Build App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          BUNDLE_IDENTIFIER: "WEDLE.Warala"
          APPLE_ID: ${{ secrets.APPLE_ID }}
        run: |
          # 자동 서명 활성화를 위한 프로젝트 설정 업데이트
          /usr/libexec/PlistBuddy -c "Set :ProvisioningStyle Automatic" PetApp.xcodeproj/project.pbxproj
          
          # Xcode Managed Profile을 사용하여 빌드
          xcodebuild -workspace PetApp.xcworkspace -scheme PetApp -configuration Release \
          -archivePath build/PetApp.xcarchive archive \
          DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
          CODE_SIGN_IDENTITY="Apple Distribution" \
          CODE_SIGN_STYLE=Automatic
      
      - name: Create Export Options Plist
        run: |
          cat > ExportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>${{ secrets.APPLE_TEAM_ID }}</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOL
      
      - name: Create IPA
        run: |
          xcodebuild -exportArchive -archivePath build/PetApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build
      
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/PetApp.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
