name: Upload to TestFlight

on:
  workflow_dispatch:
    inputs:
      ipa_path:
        description: '업로드할 IPA 파일 경로'
        required: true
        default: 'builds/app.ipa'
  
  # release 브랜치 푸시 시에도 실행
  push:
     branches: [ "release" ]

jobs:
  upload-to-testflight:
    name: Upload to TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # IPA 파일 경로 설정
      - name: Set IPA path
        id: set-ipa-path
        run: |
          # 이벤트 타입에 따라 IPA 경로 설정
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 수동 실행인 경우 입력된 경로 사용
            echo "IPA_PATH=${{ github.event.inputs.ipa_path }}" >> $GITHUB_ENV
          else
            # 푸시 이벤트인 경우 기본 경로 사용
            echo "IPA_PATH=builds/app.ipa" >> $GITHUB_ENV
          fi
          echo "Using IPA path: ${{ env.IPA_PATH }}"
      
      # IPA 파일을 저장소에 업로드했는지 확인
      - name: Verify IPA exists
        run: |
          if [ -f "${{ env.IPA_PATH }}" ]; then
            echo "✅ IPA file found at ${{ env.IPA_PATH }}"
          else
            echo "❌ IPA file not found at ${{ env.IPA_PATH }}"
            echo "Please upload your IPA file to the repository in the specified path"
            echo "Or provide a correct path when triggering this workflow"
            exit 1
          fi
      
      # App Store Connect API 키 설정
      - name: Setup App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$APP_STORE_CONNECT_API_KEY" > ~/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      
      # TestFlight에 업로드
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ env.IPA_PATH }}
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
