name: Fastlane Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Old Ruby
        run: rm -rf /Users/runner/hostedtoolcache/Ruby/*

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'


      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Run Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane beta

