name: iOS CD (Release Branch)
on:
  push:
    branches: [ "release" ]
jobs:
  deploy-to-testflight:
    name: Build and Deploy to TestFlight
    runs-on: macos-14
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      # App Store Connect API 키 설정
      - name: Setup App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo -n "$APP_STORE_CONNECT_API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      
      # Apple Developer 계정 로그인 및 프로비저닝 프로파일 새로고침
      - name: Refresh Provisioning Profiles
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcrun altool --list-providers -u "$APPLE_ID" -p "$APPLE_PASSWORD"
          
          # 프로비저닝 프로파일 새로고침 및 동기화
          xcodebuild -project PetApp.xcodeproj \
            -scheme "PetApp" \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration
      
      # 앱 빌드 및 아카이브
      - name: Build and Archive App
        run: |
          xcodebuild archive \
            -project PetApp.xcodeproj \
            -scheme "PetApp" \
            -archivePath build/app.xcarchive \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration
      
      # ExportOptions.plist 생성
      - name: Create Export Options Plist
        run: |
          cat > ExportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOL
      
      # IPA 생성
      - name: Create IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            -allowProvisioningUpdates
      
      # TestFlight에 업로드
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/*.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
